### ISSUE TITLE
error while running ctest

### ISSUE THREAD

**Issue by lenhatquang2512** [crNewton/STM32_gtest_cmake#1]
Hi, thank you for your repo.

I am also using Ubuntu 20.04 with gcc9 and I want to use gtest to test stm32 projects written with STM32CubeIDE.

I tried your code but it showed this error:
![Screenshot from 2023-07-05 22-05-24](https://github.com/crNewton/STM32_gtest_cmake/assets/72292146/f7bd7f27-bbf5-4cba-b04a-0dbce7b7b701)

Usually after make in build folder we need to call some executable file, but what exactly ctest command mean ? Can you help me with this because Im not familiar with gtest. Thank you.

**Comment by crNewton** [comment]
This project was setup because I wanted a good workflow with googletest and STM32CubeIDE.
As you did find out it works, googletest can be run. But you also found out that my test is failing. 

[ctest ](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Testing%20With%20CMake%20and%20CTest.html)is the command to find all tests in the build tree and run those. 

So it finds my [test](https://github.com/crNewton/STM32_gtest_cmake/blob/main/ExampleProject/STM32_Test/test/projectmain_test.cpp#L7), but it fails because [this](https://github.com/crNewton/STM32_gtest_cmake/blob/main/ExampleProject/STM32_Project/Project/src/projectMain.c#L21) is the function.
